# Generated by Django 4.2.6 on 2023-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadedfile_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transcript', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
