# Generated by Django 4.2.6 on 2023-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
